name: Github Pages Astro CI

on:
  # Trigger the workflow every time you push to the `github-pages-example ` branch
  # Using a different branch name? Replace `github-pages-example ` with your branch’s name
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout your repository using git
            uses: actions/checkout@v2
          - name: Install, build, and upload your site
            uses: withastro/action@v0
        # runs-on: ubuntu-latest
        # steps:
        # - name: Check out your repository using git
        #   uses: actions/checkout@v2

        # - name: Use Node.js 16
        #   uses: actions/setup-node@v2
        #   with:
        #     node-version: '16'
        #     cache: 'npm'

        # # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
        # - name: Install dependencies
        #   run: npm ci

        # # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
        # - name: Build Astro
        #   run: npm run build --if-present

        # - name: Upload artifact
        #   uses: actions/upload-pages-artifact@v1
        #   with:
        #     path: ./dist

    deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1